/**
 * Regenerate scripts/d1-seed.sql from the canonical TS seeds so the live D1
 * matches the committed demo content (posts, ministers, gallery, updates).
 *
 * Run:  bun scripts/gen-core-seed.ts
 * Apply: wrangler d1 execute mlgrd --remote --file=scripts/d1-seed.sql
 *
 * It DELETEs + re-inserts only the seed-managed tables; citizen-submitted
 * messages/appointments are never touched. Uses asset() with no base path, so
 * image paths are production-rooted ("/minister-manickchand.jpg").
 */
import { seedPosts, seedGallery, seedMinisters } from "../src/lib/data/seed";
import { seedUpdates } from "../src/lib/data/seed-updates";

const q = (v: unknown): string => {
  if (v === undefined || v === null) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  const s = Array.isArray(v) || (typeof v === "object") ? JSON.stringify(v) : String(v);
  return "'" + s.replace(/'/g, "''") + "'";
};

const row = (vals: unknown[]) => "(" + vals.map(q).join(",") + ")";

function block(table: string, cols: string, rows: string[]): string {
  return [
    `DELETE FROM ${table};`,
    `INSERT OR REPLACE INTO ${table} (${cols}) VALUES`,
    rows.join(",\n") + ";",
    "",
  ].join("\n");
}

const out: string[] = [
  "-- MLGRD core content seed (posts, ministers, gallery, updates).",
  "-- GENERATED by scripts/gen-core-seed.ts from the canonical TS seeds.",
  "-- Apply: wrangler d1 execute mlgrd --remote --file=scripts/d1-seed.sql",
  "-- Re-runnable: DELETEs + re-inserts seed tables (citizen data untouched).",
  "",
];

out.push(
  block(
    "posts",
    'id,slug,title,excerpt,body,category,tags,coverImage,sourceUrl,status,date,createdAt,updatedAt',
    seedPosts.map((p) =>
      row([p.id, p.slug, p.title, p.excerpt, p.body, p.category, p.tags ?? [], p.coverImage, p.sourceUrl, p.status, p.date, p.createdAt, p.updatedAt]),
    ),
  ),
);

out.push(
  block(
    "ministers",
    'id,name,title,portrait,initials,bio,profileUrl,termStart,termEnd,current,"order",createdAt',
    seedMinisters.map((m) =>
      row([m.id, m.name, m.title, m.portrait, m.initials, m.bio, m.profileUrl, m.termStart, m.termEnd, m.current, m.order, m.createdAt]),
    ),
  ),
);

out.push(
  block(
    "gallery",
    'id,title,caption,image,category,date,"order",createdAt',
    seedGallery.map((g) =>
      row([g.id, g.title, g.caption, g.image, g.category, g.date, g.order, g.createdAt]),
    ),
  ),
);

out.push(
  block(
    "updates",
    'id,version,date,title,summary,icon,sections,"order",createdAt',
    seedUpdates.map((u) =>
      row([u.id, u.version, u.date, u.title, u.summary, u.icon, u.sections ?? [], u.order, u.createdAt]),
    ),
  ),
);

await Bun.write("scripts/d1-seed.sql", out.join("\n"));
console.log(
  `wrote scripts/d1-seed.sql — posts:${seedPosts.length} ministers:${seedMinisters.length} gallery:${seedGallery.length} updates:${seedUpdates.length}`,
);
